[colors]
connected = "#859900"
disconnected = "#dc322f"
items = "#839496"
items_selected = "#859900"
normal_mode = "#268bd2"
search_mode = "#d33682"
connection_output = "#2aa198"
background = "#002b36"
